### ISSUE TITLE
Repeat Code

### ISSUE THREAD

**Issue by Parkerjn90** [Team-Pharos/FEC_Lighthouse#106]
#### Description
This looks like a lot of the same code that has been repeated. This probably could have been its own component where you could map over the metadata characteristics and pass each property to a set of html.  Then could have dynamically changed the name of the category and all that within the subcomponent.

#### Files
https://github.com/Team-Pharos/FEC_Lighthouse/blob/ea3107fbe3c4e0a09d1bb1dbb1747469b0fc3337/src/components/Ratings/RatingBreakdown.jsx#L26-L59

#### Tasks
- [ ] create new subcomponent
- [ ] export and import appropriately
- [ ] map over characteristics within RatingBreakdown
- [ ] pass each property into subcomponent
- [ ] dynamically render name and other details about each characteristic within the subcomponent
- [ ] profit
