### ISSUE TITLE
Close modal on submit

### ISSUE THREAD

**Issue by Parkerjn90** [Team-Pharos/FEC_Lighthouse#109]
#### Description
It would be helpful for the user if the modal closed on submit as well as on clicking the close button.  You have the method for closing the modal already imported - You'd just need to add a second instance of the function here in another .then() statement after line 139.

#### Files
https://github.com/Team-Pharos/FEC_Lighthouse/blob/ea3107fbe3c4e0a09d1bb1dbb1747469b0fc3337/src/components/Ratings/NewReviewModal.jsx#L132-L142

### Tasks
- [ ] add a .then() method after line 139
- [ ] add an anonymous function within that method
- [ ] call the "closeModal" function within that anonymous function
- [ ] Should automatically close the modal on submit now
